---
version: "2"
run:
  relative-path-mode: gomod
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
    - gci
    - golines
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    gci:
      sections:
        - standard
        - default
        - localmodule
    golines:
      max-len: 150
linters:
  default: standard
  enable:
    - depguard
    - errcheck
    - errname
    - errorlint
    - gocritic
    - gosec
    - govet
    - inamedparam
    - nlreturn
    - protogetter
    - sloglint
    - spancheck
    - testifylint
    - usestdlibvars
    - usetesting
    - usetesting
  settings:
    depguard:
      rules:
        deprecated:
          files:
            - $all
          deny:
            - pkg: github.com/golang/protobuf
              desc: Use google.golang.org/protobuf instead, see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
            - pkg: github.com/satori/go.uuid
              desc: Use github.com/google/uuid instead, satori's package is not maintained
            - pkg: github.com/gofrs/uuid$
              desc: Use github.com/gofrs/uuid/v5 or later, it was not a go module before v5
            - pkg: github.com/aws/aws-sdk-go/aws
              desc: Use github.com/aws/aws-sdk-go-v2 instead, see https://aws.github.io/aws-sdk-go-v2/docs/migrating/
    testifylint:
      enable-all: true
    errcheck:
      check-type-assertions: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict:
            true
    sloglint:
      no-mixed-args: false
      attr-only: true
      no-global: all
      msg-style: lowercased
      key-naming-case: snake
      context: scope
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
issues:
  max-same-issues: 50
