profile: coverage/cover.out
local-prefix: "github.com/creativefabrica/tinval"
threshold:
  package: 70
  total: 70
exclude:
  paths:
    - ^tinvaltest/ # exclude package `tinvaltest`
    - ^example/ # exclude package `example`
